[package]
name = "getcov"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.20"
env_logger = "0.11.5"
goblin = "0.9.0"
llvm-cov-json = "0.1.2"
log = "0.4.22"
serde_json = "1.0.132"
tempfile = "3.13.0"
thiserror = "1.0.64"
uuid = { version = "1.11.0", features = ["v4"] }
